// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Preferir env vars (Vercel). Mantém fallback constante para dev e Lovable preview.
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ?? "https://mfuxmdivnwhuczapoxik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mdXhtZGl2bndodWN6YXBveGlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0NDI3MzUsImV4cCI6MjA5MDAxODczNX0.hE62g-lpavBTdsAHuI0X7n9tWmYTmQiwabZzIZPOIYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});